### ISSUE TITLE
I'd like to repeat this analysis on other portals

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/R-projects#4]
Hi @statshero,
I'm interested in repeating the CSV analysis on Australian data portals. I don't know R. Any suggestions on getting started?

**Comment by Stephen-Gates** [comment]
Better idea... I'll pitch it to the [rOpenSci Hackathon](http://queensland.theodi.org/2016/03/10/ropensci-unconference-australia-21-22apr-2016/) in Brisbane and see if they can build on your work.

Here's [the challenge](https://github.com/ropensci/auunconf/issues/9).

**Comment by statzhero** [comment]
Hi @Stephen-Gates happy to input if that's useful!

**Comment by Stephen-Gates** [comment]
Hi @statshero feel free to join the conversation over at the challenge. After the event I may touch base about taking it further. Thanks.
